# -----------------------------
#
# Test case for functions
#
# -----------------------------

print "function without arguments"
:aFunc()
	$a = "test"
	print $a
end

aFunc
aFunc --test=asd -a asdad

:anotherFunc($internA:aaa,a $internB:bbb,b)
	print $internA
	print $internB
end

print "> non-long"
anotherFunc -asad -bgjhjk
print "> non-long (mixed spaces)"
anotherFunc -a sad -bgjhjk
print "> only long"
anotherFunc --aaa=sad --bbb=gjhjk
print "> mixed"
anotherFunc -asad --bbb=gjhjk
print "> overwritting non-long"
anotherFunc -asad -agjhjk -bhaha
print "> overwritting long"
anotherFunc --aaa=sad --aaa=gjhjk --bbb=haha
print "> overwritting mixed"
anotherFunc -asad --aaa=gjhjk -bhaha --bbb=haha


:funcWithFlag($internA:aaa,a $internFlag!flag,f)
	print $internA
	print $internFlag
end

print "> testing function with flag and flag is set"
funcWithFlag -asad -f

print "> testing function with flag and flag is not set"
funcWithFlag -asad

print "> testing function with long flag"
funcWithFlag -asad --flag

:funcWithDefaultValues($internA:aaa,a="test1")
	print $internA
end

print "testing default value - normal parameter and set value"
funcWithDefaultValues -asad

print "testing default value - normal parameter and without set value"
funcWithDefaultValues


:func($internA:aaa,a="test1")
	print $internA
end

print "testing variable replacement in string"
$var = "test"
func --aaa=/test/$var/test