# -----------------------------
#
# Test case for access range-iterator-structures
#
# -----------------------------

for $a in 1..3
	print $a
end


for $a in 3..1
	print $a
end

for $a in 1..1
	print $a
end

for $a in 0..10..2
	print $a
end


for $a in 10..0..-2
	print $a
end


for $a in 0.1..0.9
	print $a
end

for $a in 0.9..0.1
	print $a
end

for $a in 0.01..0.09
	print $a
end

for $a in 0.0..0.9..0.2
	print $a
end

for $a in 0.9..0.0..-0.2
	print $a
end